### PR TITLE
[ENH] Clean up the home page

### LINKED ISSUE #610: Clean up the landing page
The tool landing page shows

- [x] a nice clean "upload" button for the .tsv table
- [x] a nice clean "upload" button for the .json data dictionary
- [x] the "preview" textboxes are removed
- [x] all other functionality is unaffected (e.g. .json button being grey until .tsv is provided, next button ...)
- [ ] ~Upon successful upload (it didn't crash), some super simple UI element says "all good" or :heavy_check_mark:~

We still show previews for the .tsv and the .json.
- [x] preferred: nice looking table / rendered component
- [x] also good: a non-editable version of the text field we have now

### PR DESCRIPTION
**Pull request by surchs**
- Closes #610

### CODE REVIEW

File: pages/index.vue [hunk 1]
```diff
@@ -25,19 +16,23 @@
...
         <b-row>
-            <h3>{{ uiText.dataDictionaryHeader }}</h3>
+            <b-table
+                v-if="dataTable.length > 0"
+                outlined
+                sticky-header
+                :items="dataTable"
+                data-cy="data-table-display" />
+            <div v-else>
+                Please provide a data table to see a preview here.
```
Comment (rmanaem) [inline pages/index.vue:28]: :cherries: I think it'd be visually better if we had this text styled like the instruction text in the categorization page. I believe the css classs for it is `instructions-text`.

File: pages/index.vue [hunk 2]
```diff
@@ -49,6 +44,20 @@
...
+        <!-- Shows file contents -->
+        <b-row>
+            <pre
+                v-if="Object.keys(this.dataDictionary.userProvided).length > 0"
+                style="height: 200px; width: 100%; overflow: auto;"
+                data-cy="data-dictionary-display">
+                {{ stringifiedDataDictionary }}
+            </pre>
+            <div v-else>
+                Provide a data dictionary to see the preview.
```
Comment (rmanaem) [inline pages/index.vue:56]: Same as above.

**Review by rmanaem — APPROVED** [review]
Two small :cherries: other than that :cook:
